# Generated by Django 4.2 on 2023-11-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagecaption",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("hi", "Hindi"),
                    ("ta", "Tamil"),
                    ("te", "Telugu"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("es", "Spanish"),
                    ("it", "Italian"),
                    ("ja", "Japanese"),
                    ("ko", "Korean"),
                ],
                default="english",
                max_length=20,
            ),
        ),
    ]
