# Generated by Django 4.2 on 2023-11-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_imagecaption_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagecaption",
            name="image",
            field=models.ImageField(default=1, upload_to="images/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="imagecaption",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("hi", "Hindi"),
                    ("ta", "Tamil"),
                    ("te", "Telugu"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("es", "Spanish"),
                    ("it", "Italian"),
                    ("ja", "Japanese"),
                    ("korean", "ko"),
                ],
                default="english",
                max_length=20,
            ),
        ),
    ]
