# Generated by Django 4.2.7 on 2024-05-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_imagecaption_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecaption',
            name='Tcaption',
            field=models.TextField(blank=True),
        ),
    ]
